// sub-vue/src/pages/list/index.vue
<template>
  <div>list
    <div>
      <a-button @click="setToken">子应用 修改token</a-button>

      <div style="margin-top: 20px">来自主应用的token：{{$store.state.token}}</div>
    </div>
  </div>
</template>

<script>
  import dispatch from "@/shared";
  console.log(dispatch);
  export default {
    name: "index",
    methods:{
      setToken(){
        dispatch.setToken(Math.random())
      }
    }
  }
</script>

<style scoped>

</style>

// sub-react/src/pages/list/index.js
import { Button } from 'antd';
import { shallowEqual, useSelector, useDispatch } from 'react-redux'
import sharedDispatch from '../../shared'
export default function () {
  const token = useSelector(state=>state.token)
  const dispatch= useDispatch();

  const updateToken = ()=>{
    sharedDispatch.setToken(Math.random())
  }
  return (
    <div>
      <div>最新的token:{token}</div>
      <Button onClick={updateToken}>点击更新token</Button>
    </div>
  )
}
